// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdbeCA4gK6_zWLSRuAhgvT8-tymKe_VuA',
    appId: '1:860616297225:web:2a7c743f50a17bf4bee1d8',
    messagingSenderId: '860616297225',
    projectId: 'cryptocurrency-21d5c',
    authDomain: 'cryptocurrency-21d5c.firebaseapp.com',
    storageBucket: 'cryptocurrency-21d5c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8SC9xGbcuteR9QjkQHgWtTkeVqTpbYkQ',
    appId: '1:860616297225:android:7f45668d0319a689bee1d8',
    messagingSenderId: '860616297225',
    projectId: 'cryptocurrency-21d5c',
    storageBucket: 'cryptocurrency-21d5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtUw6ITlNwVIEz37EZvZ7EEjD_G22nmFA',
    appId: '1:860616297225:ios:b598cbc5a1d4cd8ebee1d8',
    messagingSenderId: '860616297225',
    projectId: 'cryptocurrency-21d5c',
    storageBucket: 'cryptocurrency-21d5c.appspot.com',
    iosBundleId: 'com.example.testGrad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtUw6ITlNwVIEz37EZvZ7EEjD_G22nmFA',
    appId: '1:860616297225:ios:b598cbc5a1d4cd8ebee1d8',
    messagingSenderId: '860616297225',
    projectId: 'cryptocurrency-21d5c',
    storageBucket: 'cryptocurrency-21d5c.appspot.com',
    iosBundleId: 'com.example.testGrad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdbeCA4gK6_zWLSRuAhgvT8-tymKe_VuA',
    appId: '1:860616297225:web:f27d707be4f5c8ddbee1d8',
    messagingSenderId: '860616297225',
    projectId: 'cryptocurrency-21d5c',
    authDomain: 'cryptocurrency-21d5c.firebaseapp.com',
    storageBucket: 'cryptocurrency-21d5c.appspot.com',
  );

}